server:
  port: 8086

spring:
  application:
    name: usuarios-service
  profiles:
    active: dev

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
  enable-hateoas: false
