server:
  port: 8088

spring:
  application:
    name: CATEGORIAS-SERVICE
  profiles:
    active: dev

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
  enable-hateoas: false
